{{- if and .Values.addons.codeserver.enabled .Values.addons.codeserver.authentikOutpost.enabled .Values.addons.codeserver.authentikOutpost.externalSecret.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "home-assistant.authentikOutpostSecretName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.addons.codeserver.authentikOutpost.externalSecret.secretStoreRef }}
  target:
    creationPolicy: Owner
    name: {{ include "home-assistant.authentikOutpostSecretName" . }}
  data:
  - secretKey: token
    remoteRef:
      key: {{ .Values.addons.codeserver.authentikOutpost.externalSecret.remoteKey }}
      property: token
{{- end }}
